[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "azure-cli"
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "azure-cli.__version__"}
